export const environment = {
  production: true,
  summaryUrl: 'https://yact.shadowfacsimile.in/api/stats/summary/',
  countriesStatsUrl: 'https://yact.shadowfacsimile.in/api/stats/countries/',
  statesStatsUrl: 'https://yact.shadowfacsimile.in/api/stats/states/',
  casesGrowthStatsUrl: 'https://yact.shadowfacsimile.in/api/growth/cases/',
  casesGrowthCountriesStatsUrl: 'https://yact.shadowfacsimile.in/api/growth/cases/countries/',
  casesGrowthFactorStatsUrl: 'https://yact.shadowfacsimile.in/api/growth/factors/',
  deathsGrowthStatsUrl: 'https://yact.shadowfacsimile.in/api/growth/deaths/',
  deathsGrowthCountriesStatsUrl: 'https://yact.shadowfacsimile.in/api/growth/deaths/countries/',
  indiaStatsUrl: 'https://yact.shadowfacsimile.in/api/stats/indiastats'
};


export const IndiaStates = {
	an: 'Andaman and Nicobar Islands',
	ap: 'Andhra Pradesh',
	ar: 'Arunachal Pradesh',
	as: 'Assam',
	br: 'Bihar',
	ch: 'Chandigarh',
	ct: 'Chhattisgarh',
	dd: 'Daman and Diu',
	dl: 'New Delhi',
	dn: 'Dadra and Nagar Haveli',
	ga: 'Goa',
	gj: 'Gujarat',
	hp: 'Himachal Pradesh',
	hr: 'Haryana',
	jh: 'Jharkhand',
	jk: 'Jammu and Kashmir',
	ka: 'Karnataka',
	kl: 'Kerala',
	la: 'Ladakh',
	ld: 'Lakshadweep',
	mh: 'Maharashtra',
	ml: 'Meghalaya',
	mn: 'Manipur',
	mp: 'Madhya Pradesh',
	mz: 'Mizoram',
	nl: 'Nagaland',
	or: 'Odisha',
	pb: 'Punjab',
	py: 'Puducherry',
	rj: 'Rajasthan',
	sk: 'Sikkim',
	tg: 'Telangana',
	tn: 'Tamil Nadu',
	tr: 'Tripura',
	up: 'Uttar Pradesh',
	ut: 'Uttarakhand',
	wb: 'West Bengal'
};